name: popgensbi_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # comment this out if cuda isn't available
  - stdpopsim
  - msprime
  - dadi
  - defopt
  - snakemake
  - zuko
  - jupyter
  - ipykernel
  - pip
  - pip:
    - sbi==v0.22.0
    - dinf
    - snakemake-executor-plugin-slurm
    - natsort
    - moments-popgen
