name: popgensbi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.6.2
  - apricot-select=0.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asciitree=0.3.3
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=24.3.0
  - aws-c-auth=0.7.4
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.3
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.13
  - aws-c-io=0.13.33
  - aws-c-mqtt=0.9.7
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.2
  - aws-sdk-cpp=1.11.156
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.3
  - bokeh=3.4.3
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - comm=0.2.1
  - contourpy=1.3.0
  - cpython=3.9.21
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - demes=0.2.3
  - distributed=2024.8.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - fasteners=0.16.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - fonttools=4.55.6
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gsl=2.7
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - heapdict=1.0.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.5.0
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=2.2.1
  - libabseil=20230802.1
  - libarrow=13.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.7
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.51
  - libgrpc=1.58.1
  - libhwloc=2.11.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=4.24.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libthrift=0.19.0
  - libtiff=4.3.0
  - libudev1=257.2
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=12.0.1
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - msprime=1.3.3
  - munkres=1.1.4
  - mysql=5.7.20
  - nbclassic=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.5
  - nbconvert-core=7.16.5
  - nbconvert-pandoc=7.16.5
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nose=1.3.7
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numba=0.60.0
  - numcodecs=0.12.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - olefile=0.47
  - openblas=0.3.28
  - opencl-headers=2024.10.24
  - openjpeg=2.4.0
  - openldap=2.6.4
  - openssl=3.4.0
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - pomegranate=1.0.0
  - pooch=1.8.2
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=13.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.2.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-lmdb=1.6.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.2
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - rdma-core=55.0
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - s2n=1.3.54
  - scikit-allel=1.3.8
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - svgwrite=1.4.3
  - tbb=2021.13.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - toolz=1.0.0
  - torchtriton=3.1.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - tskit=0.6.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - ucx=1.15.0
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zarr=2.13.3
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - arviz==0.17.1
      - grpcio==1.70.0
      - h5netcdf==1.5.0
      - markdown==3.7
      - matplotlib==3.9.4
      - nflows==0.14
      - opt-einsum==3.4.0
      - pillow==11.1.0
      - protobuf==5.29.3
      - pyknos==0.16.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytz==2024.2
      - sbi==0.22.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tqdm==4.67.1
      - tzdata==2025.1
      - werkzeug==3.1.3
      - xarray==2024.7.0
      - xarray-einstats==0.7.0
