name: popgensbi
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - snakemake
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - sbi==v0.22.0
    - dinf
    - snakemake-executor-plugin-slurm
    - natsort
